services:
  #source :https://hub.docker.com/r/heartexlabs/label-studio
  label_studio:
    image: img_annotations/label_studio_with_deps
    build: 
      context: ./label_studio_image
    container_name: img-annotations-label-studio #use characters that are valid for URL. For instance, this example will FAIL : curl -X GET http://img_annotations_label_studio:8080/api/projects/ -H 'Authorization: Token $MYTOKEN'
    env_file:
      - path: ./label_studio_image/label_studio_secrets.env #set LABELSTUDIO_API_KEY in this file
      - path: ./label_studio_image/label_studio.env
    ports:
      - 8080:8080
    volumes:
      - ./label_studio_data:/label-studio/data
      - ./local_images:/home/local_images     

  sa2_label_studio_cpu:
    profiles: [cpu]
    container_name: img-annotations-sa2-label-studio
    extends:
      file: label_studio_sa2_image/sa2_label_studio.yaml
      service: sa2_label_studio
    environment:
      - DEVICE=cpu

  sa2_label_studio_gpu:
    profiles: [gpu]
    container_name: img-annotations-sa2-label-studio
    extends:
      file: label_studio_sa2_image/sa2_label_studio.yaml
      service: sa2_label_studio
    environment:
      - DEVICE=cuda      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  fiftyone_cpu:
    profiles: [cpu]
    container_name: img-annotations-fiftyone #use characters that are valid for URL. See remarks above
    extends:
      file: fiftyone_image/fiftyone_compose.yaml
      service: fiftyone

  fiftyone_gpu:
    profiles: [gpu]
    container_name: img-annotations-fiftyone #use characters that are valid for URL. See remarks above
    extends:
      file: fiftyone_image/fiftyone_compose.yaml
      service: fiftyone
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]      

  mongodb:
    image: mongo
    container_name: img-annotations-mongodb #use characters that are valid for URL. See remarks above
    env_file:
      - path: ./fiftyone_image/fiftyone_secrets.env #set MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD in this file
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./mongodb_data
        target: /data/db      

volumes:
  label_studio_data:
  label_studio_sa2_data:
  local_images:
  fiftyone_data:
  mongodb_data:
