services:
  #source :https://hub.docker.com/r/heartexlabs/label-studio
  label_studio:
    profiles: [cpu, gpu, label-studio]
    image: img-ann/label-studio
    build: 
      context: ./label_studio_image
    container_name: img-ann-label-studio #use characters that are valid for URL. For instance, this example will FAIL : curl -X GET http://img_annotations_label_studio:8080/api/projects/ -H 'Authorization: Token $MYTOKEN'
    env_file:
      - path: ./label_studio_image/label_studio_secrets.env #set LABELSTUDIO_API_KEY in this file
      - path: ./label_studio_image/label_studio.env
    ports:
      - 8080:8080
      - 8081:8081 #for the jupyter notebook running in this container      
    volumes:
      - ./label_studio_data:/label-studio/data
      - ./PythonUtils:/home/PythonUtils
      - ./local_images:/home/local_images
    networks:
      - img-ann-net         

  sa2_label_studio_cpu:
    profiles: [cpu, cpu-sa2-label-studio]
    container_name: img-ann-sa2-label-studio
    extends:
      file: label_studio_sa2_image/sa2_label_studio.yaml
      service: sa2_label_studio
    networks:
      - img-ann-net      
    environment:
      - DEVICE=cpu

  sa2_label_studio_gpu:
    profiles: [gpu, gpu-sa2-label-studio]
    container_name: img-ann-sa2-label-studio
    extends:
      file: label_studio_sa2_image/sa2_label_studio.yaml
      service: sa2_label_studio
    networks:
      - img-ann-net      
    environment:
      - DEVICE=cuda      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  fiftyone_cpu:
    profiles: [cpu, cpu-fiftyone]
    container_name: img-ann-fiftyone #use characters that are valid for URL. See remarks above
    extends:
      file: fiftyone_image/fiftyone_compose.yaml
      service: fiftyone
    networks:
      - img-ann-net

  fiftyone_gpu:
    profiles: [gpu, gpu-fiftyone]
    container_name: img-ann-fiftyone #use characters that are valid for URL. See remarks above
    extends:
      file: fiftyone_image/fiftyone_compose.yaml
      service: fiftyone
    networks:
      - img-ann-net      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]      

  mongodb:
    profiles: [cpu, gpu, mongodb]
    image: mongo
    container_name: img-ann-mongodb #use characters that are valid for URL. See remarks above
    env_file:
      - path: ./fiftyone_image/fiftyone_secrets.env #set MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD in this file
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./mongodb_data
        target: /data/db   
    networks:
      - img-ann-net

volumes:
  label_studio_data:
  label_studio_sa2_data:
  local_images:
  fiftyone_data:
  mongodb_data:

networks:
  img-ann-net:
    name: img-ann-net  # Explicit name so that you can connect other containers on this network
    driver: bridge
