services:
  #source :https://hub.docker.com/r/heartexlabs/label-studio
  label_studio:
    image: heartexlabs/label-studio:latest
    container_name: img_annotations_label_studio
    env_file:
      - path: ./label_studio.env
      - path: ./label_studio_secrets.env
        required: false
    ports:
      - 8080:8080
    volumes:
      - ./label_studio_data:/label-studio/data
      - ./local_images:/home/local_images     
      - ./requirements:/home/requirements
    command: >      
      bash -c "ls -lah /home
      && python -m pip install -U pip
      && pip install -r /home/requirements/pip_requirements_all.txt
      && label-studio"
  
  #source : https://hub.docker.com/r/voxel51/fiftyone
  fiftyone:
    image: img_annotations/fiftyone_with_deps
    build: ./fiftyone_image
    container_name: img_annotations_fiftyone
    env_file:
      - path: ./fiftyone_image/fiftyone.env 
      - path: ./fiftyone_image/fiftyone_secrets.env #set FIFTYONE_LABELSTUDIO_API_KEY in this file
        required: false           
    ports:
      - 5151:5151
    volumes:
      - type: bind
        source: ./fiftyone_data
        target: /fiftyone
      - ./local_images:/home/local_images
      - ./requirements:/home/requirements

volumes:
  label_studio_data:
  local_images:
  fiftyone_data:
